name: Our Push
on:
  push:
    branches: [main]
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ref_name=${{ github.ref_name }}"
      - run: echo "sha=${{ github.sha }}"
      - run: echo "name=${{ github.event_name }}"
      
